tda:
  default-connection:
    connection-name: TDengine
    enable: true
    auth-type: UserPassword
    url: http://tdengine-tsdb:6041
    username: root
    password: taosdata
    explorer-url: http://tdengine-tsdb:6060
  default-tdengine-db-name: idmp # default database used for IDMP in each TDengine connection
  phone-server-enabled: true
  easy-config:
    server-ip: 192.168.100.36