services:
  tdengine-tsdb-it:
    image: image.pre.cloud.taosdata.com/tdengine/tsdb-it:latest
    container_name: tdengine-tsdb
    hostname: tdengine
    restart: always
    environment:
      TZ: "${TZ:-UTC}"
      TAOS_DISABLE_EXPLORER: "1"
      TAOS_DISABLE_TAOSX: "1"
      TAOS_DISABLE_KEEPER: "1"
    ports:
      - "6030:6030"
      - "6041:6041"
    volumes:
      - tsdb_data:/var/lib/taos
      - tsdb_log:/var/log/taos
      - ../init-anode.sql:/docker-entrypoint-initdb.d/init-anode.sql
    networks:
      - taos_net
    healthcheck:
      test: ["CMD", "taos", "-h", "localhost", "-s", "show databases;"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  tdengine-idmp-it:
    image: image.pre.cloud.taosdata.com/tdengine/idmp-it:latest
    container_name: tdengine-idmp-it
    restart: always
    depends_on:
      tdengine-tsdb-it:
        condition: service_healthy
    environment:
      TZ: "${TZ:-UTC}"
      TSDB_URL: "http://tdengine-tsdb:6041"
      VITE_MENU_TYPE: "it_monitoring"
      TDA_ANALYSIS_EVENT_URLS: "ws://tdengine-idmp:6042"
      QUARKUS_PROFILE: "external"
      IDMP_URL: "${IDMP_URL:-http://localhost:6042}"
    ports:
      - "6038:6038"
      - "6042:6042"
    volumes:
      - idmp_data:/var/lib/taos
      - idmp_log:/var/log/taos
      - ./application-external.yml:/usr/local/taos/idmp/config/application-external.yml
      # - ./application.yml:/usr/local/taos/idmp/config/application.yml
    networks:
      - taos_net
    healthcheck:
      test: [ "CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:6042').read()" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  taos_net:
    driver: bridge

volumes:
  tsdb_data:
    driver: local
  tsdb_log:
    driver: local
  idmp_data:
    driver: local
  idmp_log:
    driver: local