TSDB_CONFIG:
#  key1: value1
#  key2: value2

IDMP_CONFIG:
  tda:
    default-connection:
      connection-name: TDengine
      enable: true
      auth-type: UserPassword
      url: http://tdengine-tsdb:6041
      username: root
      password: taosdata
      explorer-url: http://tdengine-tsdb:6060
    default-tdengine-db-name: idmp # default database used for IDMP in each TDengine connection
    phone-server-enabled: true
    easy-config:

TDGPT_CONFIG:
  #enable: true
  #api_key: "abc123"
